name: Promote staging to prod

on:
  # allow manual run
  workflow_dispatch:
  push:
    branches:
    - master
    # trigger only when listed files were modified
    paths:
    - promote-env/env/staging/version.yaml

# override default permission set on GITHUB_TOKEN
# permissions:
#   contents: write
#   pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git checkout -B staging/${{ github.sha }}
        # promote
        cp promote-env/env/staging/version.yaml promote-env/env/prod/version.yaml
        git add promote-env/env/prod/version.yaml
        git commit -m "Promote stating to prod"
        git push origin staging/${{ github.sha }}
