name: Promote staging to prod

on:
  # allow manual run
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - promote-env/env/staging/version.yaml

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
