name: Promote staging to prod

on:
  # allow manual run
  workflow_dispatch:
  push:
    branches:
    - master
    # trigger only when listed files were modified
    paths:
    - promote-env/env/staging/version.yaml

# override default permission set on GITHUB_TOKEN
permissions:
  # required to push branch
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git config --global user.email "bob.jones@gmail.com"
        git config --global user.name "Bob Jones"
        git checkout -B staging/${{ github.sha }}
        # promote
        cp promote-env/env/staging/version.yaml promote-env/env/prod/version.yaml
        git add promote-env/env/prod/version.yaml
        git commit -m "Promote stating to prod"
        git push origin staging/${{ github.sha }}
    - run:
        # github CLI
        gh pr create \
        -B master \
        -H staging/${{ github.sha }} \
        --title "Promote stating to prod" \
        --body "Automatically created by workflow"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
